language: java
jdk: openjdk8
sudo: false
script: mvn clean install -Dmaven.javadoc.skip=true -B -V
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: kartikbvarma@icloud.com
  password:
    secure: IbNplwQEcxXqz+Ws+qUqN75maa/hQXt0SahkODn9WxWKnMjxKVL85bjLxvgTg4QyUPEobBDCPKEPLjRrM9MfoKHj6Pp98DC6dOsWZyrJlTKgAhY/tTnDLwbz7FYtAsxC5rVYJ51HsJ+xgd+J2RQrYpI2kcLUULzfmV6mSUNN/3+u5rk8yOBUnx+rg+5456p2a+baXtmJ+AukGAbch/MW2UzR6NactDANmyh1XdSjCsdbnglj5s36dEDbJXTiIcMP6OzlSs/w4LKkkAL0W9GOOmB2BxmF4MTt7pW1iFG3k9fPYWyq8dqlwfgkHLrshewBfqrzPE4SfUCshCOsbkZPtTpA7c9jVw+Q49HamlOxaWFpLenoaA/hK1Tm/hGLF+YIpls79c2VfDCj4ISHSVXXjXYegn/J6BR1FLj31cHjuB5tzWi/++paLKqE0eOQcHEH15G6pZ+63TXgcvB4+rQBgArOkCVQn+9hZjxSITMvX5K9HmrDDDXs3Pl2flPOIHUXq04o//XzCYWfp8J8UOUCDIeuaxTs6Eb9ZNXICdbm10eLTPBtyJGJLwBzm4gaEgVIDHCX0/maqjPB4VWQwBxDYi2otcjdtgAB3jqjG5GSryQaOCpb54kGMDb8lMWTUKRQQ5+tALCc/FcQC+OIZGcfMZCO9B9pKmsRK1KrmkxIhrQ=
  organization: KnowledgeByProof
  space: development
  on:
    repo: kartikvarma/spring-react
